/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ty_android_ndkdemo_NdkLib */

#ifndef _Included_com_ty_android_ndkdemo_NdkLib
#define _Included_com_ty_android_ndkdemo_NdkLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ty_android_ndkdemo_NdkLib
 * Method:    getStringFromNdk
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ty_android_ndkdemo_NdkLib_getStringFromNdk(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
